public class MachineProblem1 {
    public static void main(String[] args) {
        System.out.println("How do I love thee?");
        System.out.println("Let me count the ways.");
        System.out.println("I love thee to the depth and");
        System.out.println("breadth and height");
        System.out.println("My soul can reach,");
        System.out.println("when feeling out of sight");
        System.out.println("For the ends of Being and ideal Grace.");
        System.out.println("I love thee to the level of everyday's");
        System.out.println("Most quiet need,");
        System.out.println("by sun and candle-light.");
        System.out.println("I love thee freely,");
        System.out.println("as men strive for Right;");
        System.out.println("I love thee purely,");
        System.out.println("as they turn from Praise.");
        System.out.println("I love thee with a passion put to use");
        System.out.println("In my old griefs,");
        System.out.println("and with my childhood's faith.");
        System.out.println("I love thee with a love I seemed to lose");
        System.out.println("With my lost saints,");
        System.out.println("I love thee with the breath,");
        System.out.println("Smiles, tears, of all my life!");
        System.out.println("I shall but love thee better after death.");
    }
}

